### ISSUE TITLE
remove api key

### ISSUE THREAD

**Issue by Jerrry-10** [9Mohamedismail/Group-Hangout-Planner#3]
> Do not push an api key ever 

 _Originally posted by @Jerrry-10 in [a238440](https://github.com/9Mohamedismail/Group-Hangout-Planner/commit/a23844047bbaf84ce683df027f18a05e08960ade#r150430056)_

**Comment by 9Mohamedismail** [comment]
fixed, thank you

**Comment by Jerrry-10** [comment]
This is not fixed

https://github.com/9Mohamedismail/Group-Hangout-Planner/blob/e753befd188dc900687b46099276b16a1211ada2/src/config/firebase.js#L5

**Comment by 9Mohamedismail** [comment]
Previous comment was sent before commit was pushed, it should now be working
